export default {
  type: String,
  placeholder: String,
  maxlength: Number,
  minlength: Number,
  max: Number,
  min: Number,
  name: String,
  value: [String, Number, Object, Array],
  disabled: Boolean,
  readonly: Boolean,
  autofocus: Boolean,
  data: {},
  resize: String,
};
